export default {
    "contactPersonId": null,
    "dataAreaId": "dat",
    "educationLevel": 0,
    "inipa": "192-310-601 36",
    "lastName": "Анатолий22",
    "firstName": "из конверта",
    "middleName": "Игоревич",
    "name": "Анатолий из конверта Игоревич",
    "contactPersonNameGenitive": "Федорова Тест5 Игоревича",
    "gender": 2,
    "birthDate": "10.07.2010 00:00",
    "birthPlace": "Тестовград",
    "otherCountryRegionId": "РФ",
    "identityCardCode": "Паспорт РФ",
    "identityCardSeries": "5811",
    "identityCardNumber": "087580",
    "identityCardIssueBy": "ТП №59 отдела УФМС России по Санкт-Петербургу и Ленинградской обл. в Петроградском р-не гор. Санкт-Петербурга",
    "identityCardIssueDep": "725-125",
    "identityCardIssueDate": "13.07.2010 00:00",
    "isHotel": 0,
    "langInfo": 0,
    "isCompatriot": 0,
    "email": "testFred1@gmail.com",
    "cellularPhone": "88000013535",
    "homePhoneNumber": "235642",
    "modifiedBy": "TSST",
    "recId": null,
    "application": {
        "deliveryType": 0,
        "docReturnType": 0,
        "applDate": "01.01.2016 00:00",
        "studentNum": "16030002",
        "changeEnvBudget": 0,
        "docType": 1,
        "grantDateOriginal": "15.03.2007 00:00",
        "courseNumber": 1,
        "isDocReturn": 0,
        "docReturnDate": "01.01.1900 00:00",
        "docReturnReasonId": "",
        "companyId": "2019-1",
        "applicationLines": [
            {
                "appLineId": "1",
                "priority": 2,
                "refNum": "",
                "refDate": "01.01.2019 00:00",
                "contrNum": "",
                "contrDate": "01.01.1900 00:00",
                "orgName": "",
                "deparCode": "0100",
                "specialityId": "ГастроЭнт",
                "environmentId": "Договор",
                "envIdChange": "",
                "eduForm": 1,
                "targOrgId": "",
                "compGroupsId": "",
                "compGroupLineId": "",
                "agreements": [
                    {
                        "orderGroupType": 4,
                        "refTableId": 51222,
                        "refusalDate": "01.01.1900 00:00",
                        "agreementDate": "01.01.2019 00:00"
                    }
                ]
            }
        ],
        "applicationDocs": [
            {
                "documentId": "021",
                "docSeries": "ВСВ",
                "docNumber": "1065139",
                "docIssueDate": "12.05.2009 00:00",
                "docIssueBy": "СЗГМУ им. И.И. Мечникова",
                "docName": "Диплом о высшем профессиональном образовании Серия ВСВ № 1065139 от 11.06.2008 выданный СЗГМУ им. И.И. Мечникова (Копия)",
                "docType": 0,
                "docQuantity": 1,
                "altDocName": "",
                "docGrantDate": "01.01.1900 00:00",
                "documentKindId": "",
                "isauto": 0
            }
        ]
    },
    "parents": [
        {
            "contactPersonId": null,
            "dataAreaId": "dat",
            "educationLevel": 0,
            "inipa": "192-310-601 36",
            "lastName": "Родитель",
            "firstName": "Тест",
            "middleName": "Степанович",
            "name": "Федоров Тест Степанович",
            "contactPersonNameGenitive": "Родитель Тест2а Степановича",
            "gender": 2,
            "birthDate": "10.07.1970 00:00",
            "birthPlace": "Тестовград",
            "otherCountryRegionId": "",
            "identityCardCode": "Паспорт РФ",
            "identityCardSeries": "2323",
            "identityCardNumber": "2323423",
            "identityCardIssueBy": "ТП №59 отдела УФМС России по Санкт-Петербургу и Ленинградской обл. в Петроградском р-не гор.Санкт-Петербурга",
            "identityCardIssueDep": "725-125",
            "identityCardIssueDate": "13.07.2010 00:00",
            "isHotel": 0,
            "langInfo": 0,
            "isCompatriot": 0,
            "email": "testman@gmail.com",
            "cellularPhone": "88001113535",
            "homePhoneNumber": "321724",
            "modifiedBy": "",
            "recId": null,
            "contactPersonPk": {
                "contactPersonId": null,
                "dataAreaId": "dat",
                "eduLevelId": "003",
                "soldieryId": "Невоеннообязанный",
                "soldieryStatus": 0,
                "militaryFormDoc": 0,
                "militarySeries": "",
                "militaryNumber": "",
                "militaryIssueBy": "",
                "militaryIssueDate": "01.01.1900 00:00",
                "militaryRank": "",
                "soldieryBegDate": "01.01.1900 00:00",
                "soldieryEndDate": "01.01.1900 00:00",
                "militaryDocType": 0,
                "militaryDocGrantDate": "01.01.1900 00:00",
                "eduCrimea": 0,
                "eduCountryRegionId": "РФ",
                "eduState": "Приморский",
                "acadamyYearId": "2015",
                "instName": "",
                "eduDocId": "Диплом",
                "eduCardSeries": "ЭВ",
                "eduCardNumber": "757237",
                "eduCardIssueDate": "13.07.2019 00:00",
                "eduCardIssueBy": "",
                "eduCardApplSeries": "",
                "eduCardApplNumber": "0551826",
                "meanScoreEduDoc": 5,
                "specConditions": "Не требуется",
                "highSchoolId": "",
                "qualificationLevelId": "",
                "specialityId": "",
                "specDescription": "",
                "eduStartDate": "13.07.2019 00:00",
                "qualDescription": "",
                "sacDate": "13.07.2019 21:20",
                "scienceWorksQty": 17,
                "otherDocName": "",
                "isAccreditationLikeExam": 0,
                "accreditationDocId": "",
                "accreditationSeries": "",
                "accreditationNumber": "",
                "accreditationIssueDate": "01.01.1900 00:00",
                "accreditationIssueBy": "",
                "accreditationDocType": -1,
                "accreditationGrantDateOriginal": "01.01.1900 00:00",
                "employDays": 0,
                "employMonths": 0,
                "employYears": 0,
                "isForeigners": 0,
                "accreditationScore": 0,
                "inipaDate": "13.07.2010 00:00",
                "modifiedBy": "TSST",
                "recId": null
            },
            "fiasAddress": [
                {
                    "addrTableTd": 520,
                    "addrRecId": "",
                    "addressType": 0,
                    "lineNum": 1,
                    "countryRegionId": "РФ",
                    "countryRegionName": "Россия",
                    "aoLevel1": 1,
                    "aoLevel1ObjRef": "c2deb16a-0330-4f05-821f-1d09c93331e6",
                    "aoLevel1ObjName": "Санкт-Петербург г",
                    "aoLevel2": 0,
                    "aoLevel2ObjRef": "",
                    "aoLevel2ObjName": "",
                    "aoLevel3": 0,
                    "aoLevel3ObjRef": "",
                    "aoLevel3ObjName": "",
                    "aoLevel4": 0,
                    "aoLevel4ObjRef": "",
                    "aoLevel4ObjName": "",
                    "aoLevel5": 0,
                    "aoLevel5ObjRef": "",
                    "aoLevel5ObjName": "",
                    "aoLevel6": 0,
                    "aoLevel6ObjRef": "",
                    "aoLevel6ObjName": "",
                    "aoLevel7": 7,
                    "aoLevel7ObjRef": "56971303-9731-4e84-b737-7b2020d38f5d",
                    "aoLevel7ObjName": "Боткинская ул",
                    "aoLevel90": 0,
                    "aoLevel90ObjRef": "",
                    "aoLevel90ObjName": "",
                    "aoLevel91": 0,
                    "aoLevel91ObjRef": "",
                    "aoLevel91ObjName": "",
                    "houseRef": "78048f15-89e3-4a28-a47f-935ec875df89",
                    "houseName": "д.15 корп.2",
                    "flat": "21",
                    "postalCode": "194044",
                    "kladrCode": "78000000000018900",
                    "addressTxt": "Россия, Санкт-Петербург г, Боткинская ул, д.15 корп.2, кв.21",
                    "addressTxt_random": "",
                    "aoLevel65": 0,
                    "aoLevel65ObjRef": "",
                    "modifiedBy": "TSST",
                    "aoLevel65ObjName": ""
                }
            ]
        }
    ],
    "entrantPreferences": [
        {
            "modifiedBy": "TST",
            "preferenceId": "AT012",
            "prefType": 0,
            "sourceType": 1,
            "typeDiploma": 0,
            "nameOlympiad": "",
            "chemistry": 0,
            "biology": 1,
            "appLineId": "",
            "isPrefApprove": 0,
            "pointRandom": 0,
            "yearCount": 0,
            "pointFisExport": 0,
            "isShow": 0,
            "preferenceDocs": [
                {
                    "modifiedBy": "TST",
                    "documentId": "015",
                    "docSeries": "АБ",
                    "docNumber": "55596932а",
                    "docIssueDate": "01.01.2008 00:00",
                    "docIssueBy": "Отделом ВК С-ПБ по Выборгскому району",
                    "docName": "Диплом победителя/призера олимпиады школьников Серия 234234 № 23423423423423 от 24.05.2017 выдан ОргКом (Копия)",
                    "docType": 0,
                    "docQuantity": 1,
                    "altDocName": "",
                    "docGrantDate": "01.01.2010 00:00",
                    "isDublicate": 0,
                    "documentKindId": ""
                }
            ]
        }
    ],
    "subjectScores": [
        {
            "modifiedBy": "TST",
            "subjectId": "Биол",
            "examForm": 10,
            "dataAreaId": "dat",
            "examPoint": 50,
            "examNote": 0,
            "examPoint_test": 0,
            "examPoint_interview": 0,
            "examListNum": "",
            "examListDate": "01.07.2019 00:00",
            "eisExamPoint": 0
        }
    ],
    "contactPersonPk": {
        "contactPersonId": null,
        "dataAreaId": "dat",
        "eduLevelId": "003",
        "soldieryId": "Невоеннообязанный",
        "soldieryStatus": 0,
        "militaryFormDoc": 0,
        "militarySeries": "",
        "militaryNumber": "",
        "militaryIssueBy": "",
        "militaryIssueDate": "01.01.1900 00:00",
        "militaryRank": "",
        "soldieryBegDate": "01.01.1900 00:00",
        "soldieryEndDate": "01.01.1900 00:00",
        "militaryDocType": 0,
        "militaryDocGrantDate": "01.01.1900 00:00",
        "eduCrimea": 0,
        "eduCountryRegionId": "РФ",
        "eduState": "Приморский",
        "acadamyYearId": "2015",
        "instName": "",
        "eduDocId": "Диплом",
        "eduCardSeries": "ЭВ",
        "eduCardNumber": "757237",
        "eduCardIssueDate": "13.07.2019 00:00",
        "eduCardIssueBy": "Ленинградский санитарно-гигиенический медицинский институт",
        "eduCardApplSeries": "ВСВ",
        "eduCardApplNumber": "0551826",
        "meanScoreEduDoc": 5,
        "specConditions": "Не требуется",
        "highSchoolId": "HS0156",
        "qualificationLevelId": "Врач",
        "specialityId": "ЛечДел",
        "specDescription": "",
        "eduStartDate": "13.07.2019 00:00",
        "qualDescription": "",
        "sacDate": "13.07.2019 21:20",
        "scienceWorksQty": 17,
        "otherDocName": "",
        "isAccreditationLikeExam": 0,
        "accreditationDocId": "",
        "accreditationSeries": "",
        "accreditationNumber": "",
        "accreditationIssueDate": "01.01.1900 00:00",
        "accreditationIssueBy": "",
        "accreditationDocType": -1,
        "accreditationGrantDateOriginal": "01.01.1900 00:00",
        "employDays": 0,
        "employMonths": 0,
        "employYears": 0,
        "isForeigners": 0,
        "accreditationScore": 0,
        "inipaDate": "13.07.2010 00:00",
        "modifiedBy": "TSST",
        "recId": null
    },
    "fiasAddress": [
        {
            "addrTableTd": 520,
            "addrRecId": "",
            "addressType": 0,
            "lineNum": 1,
            "countryRegionId": "РФ",
            "countryRegionName": "Россия",
            "aoLevel1": 1,
            "aoLevel1ObjRef": "c2deb16a-0330-4f05-821f-1d09c93331e6",
            "aoLevel1ObjName": "Санкт-Петербург г",
            "aoLevel2": 0,
            "aoLevel2ObjRef": "",
            "aoLevel2ObjName": "",
            "aoLevel3": 0,
            "aoLevel3ObjRef": "",
            "aoLevel3ObjName": "",
            "aoLevel4": 0,
            "aoLevel4ObjRef": "",
            "aoLevel4ObjName": "",
            "aoLevel5": 0,
            "aoLevel5ObjRef": "",
            "aoLevel5ObjName": "",
            "aoLevel6": 0,
            "aoLevel6ObjRef": "",
            "aoLevel6ObjName": "",
            "aoLevel7": 7,
            "aoLevel7ObjRef": "56971303-9731-4e84-b737-7b2020d38f5d",
            "aoLevel7ObjName": "Боткинская ул",
            "aoLevel90": 0,
            "aoLevel90ObjRef": "",
            "aoLevel90ObjName": "",
            "aoLevel91": 0,
            "aoLevel91ObjRef": "",
            "aoLevel91ObjName": "",
            "houseRef": "78048f15-89e3-4a28-a47f-935ec875df89",
            "houseName": "д.15 корп.2",
            "flat": "21",
            "postalCode": "194044",
            "kladrCode": "78000000000018900",
            "addressTxt": "Россия, Санкт-Петербург г, Боткинская ул, д.15 корп.2, кв.21",
            "addressTxt_random": "",
            "aoLevel65": 0,
            "aoLevel65ObjRef": "",
            "modifiedBy": "TSST",
            "aoLevel65ObjName": ""
        }
    ],
    "entrantComments": [
        {
            "commentId": "",
            "description": "",
            "recVersion": 0
        }
    ],
    "entrantLanguages": [
        {
            "languageId": "Английский",
            "score": 4
        }
    ],
    "egeCertificates": [
        {
            "egeCertificateId": null,
            "dataAreaId": "",
            "contactPersonId": "",
            "egeCertificateNumber": "",
            "printingNumber": "125887536",
            "egeCertificateIssueDate": "01.07.2019 00:00",
            "docType": -1,
            "identityCardIssueDate": "01.07.2000 00:00",
            "identityCardSeries": "4587",
            "identityCardNumber": "98425252",
            "identityCardIssueBy": "ОУФМС России по Ростовской области в городе Красный Сулин",
            "identityCardCode": "87-89",
            "examFormEge": 0,
            "locationEge": "ГБОУ СОШ №518",
            "yearDeliveryEge": "2019",
            "egeCertificateGrantDate": "01.07.2019 00:00",
            "certificateStatus": 2,
            "document": 0,
            "docFirstName": "",
            "docMiddleName": "",
            "docLastName": "",
            "otherCountyRegionId": "КАЗАХСТАН",
            "modifiedBy": "TSST",
            "egeSubjects": [
                {
                    "modifiedBy": "CCKS",
                    "subjectId": "РусскЯз",
                    "score": 100,
                    "scoreFis": 90,
                    "orderBy": 3,
                    "lastCheckDate": "18.07.2019 00:00",
                    "egeAppealStatus": 1
                }
            ]
        },
        {
            "egeCertificateId": null,
            "dataAreaId": "",
            "contactPersonId": "",
            "egeCertificateNumber": "",
            "printingNumber": "4458554755",
            "egeCertificateIssueDate": "01.07.2019 00:00",
            "docType": -1,
            "identityCardIssueDate": "01.07.2000 00:00",
            "identityCardSeries": "1111",
            "identityCardNumber": "98425252",
            "identityCardIssueBy": "ОУФМС России по Ростовской области в городе Красный Сулин",
            "identityCardCode": "87-89",
            "examFormEge": 0,
            "locationEge": "ГБОУ СОШ №518",
            "yearDeliveryEge": "2019",
            "egeCertificateGrantDate": "01.07.2019 00:00",
            "certificateStatus": 2,
            "document": 0,
            "docFirstName": "",
            "docMiddleName": "",
            "docLastName": "",
            "otherCountyRegionId": "КАЗАХСТАН",
            "modifiedBy": "TSST",
            "egeSubjects": [
                {
                    "modifiedBy": "KISS",
                    "subjectId": "Биол",
                    "score": 100,
                    "scoreFis": 90,
                    "orderBy": 3,
                    "lastCheckDate": "21.07.2019 00:00",
                    "egeAppealStatus": 1
                }
            ]
        }
    ]
}
